CREATE TABLE IF NOT EXISTS contacts (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  email text not null,
  phone text
);

CREATE TABLE IF NOT EXISTS alerts (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  alert_type text not null,
  message text,
  contacts_notified text,
  resolved boolean default false
);

-- Desativar RLS (Row Level Security) para testes locais
ALTER TABLE contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE alerts DISABLE ROW LEVEL SECURITY;
